project:
  type: website
  output-dir: docs

website:
  title: "Local 21HD"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: contracts.qmd
        text: Contracts
      - href: bargaining.qmd
        text: Bargaining

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

