---
title: "Bargaining 101"
---

### What is bargaining?

Bargaining is when we (Local 21HD) negotiate with the County to set our pay, benefits, and working conditions. For Local21HD, bargaining occurs in two phases: (1) bargaining between the Coalition of Unions and King County, and (2) Local 21HD "small table" bargaining.

#### Coalition of Unions and King County Bargaining

Local 21HD joins with many other unions that represent King County staff to jointly bargain with King County. The [Coalition Labor Agreement](https://kingcounty.gov/~/media/depts/executive/labor-relations/documents/contracts/Final_CLA2021-2024.ashx) generally covers the "big" ticket items like Cost of Living Increases (also know as General Wage Increases), leave (e.g. vacation), health benefits (kind of), and other benefits (e.g. paid parental leave, professional development, child care). It is the result of this process to which the Local 21HD specific issues/negotiations are append.

These bargaining sessions are mostly carried out by the Coalition Co-Chairs (e.g. staff representatives and each member of the coalition sends a member or two to participate (usually the President or designee). By joining with other unions, we generate strength through numbers.

#### Local 21HD "small table" Bargaining

We (Local 21HD) bargain with the County on a number of specific topics. The Local 21HD bargaining is guided by our staff representative and generally includes at least one member from each job classification. Relevant topics include:

1.  Higher pay ranges
2.  Triggering bureaucratic reviews (e.g. determining the need to update our job classifications)
3.  Comp time and over time rules
4.  Layoff language
5.  Bilingual premium

The current status of all of these topics [Local21HD Specific Agreement/Appendix](https://kingcounty.gov/~/media/depts/executive/labor-relations/documents/contracts/Final_070CLAC0122.ashx).

### When is bargaining?

Our contracts conclude at the end of 2024. We expect Coalition bargaining will begin in late spring/early summer with small table bargaining to follow. Ideally, everything is nice and done by the end of 2024. However, the last cycle didn't complete until 2022 (after starting in 2020/2021).

### How will Local21HD faithfully represent its members

At a minimum, we will conduct a survey of members to gauge priorities. We hope to supplement this survey with focus groups, drop-in sessions, and other approaches to make sure we have the best data/information available. We also hope to form an active and diverse bargaining committee to advocate for the will of L21HD members. We will scale up our preparation in late March/early April 2024.
