---
title: "Home"
---

## [Know your rights](https://www.nlrb.gov/about-nlrb/rights-we-protect/your-rights)

Our [contract(s)](contracts.qmd) specify most our the rules related to our pay, benefits, and working conditions. Additional rights are enshrined by local, state, and [federal law](https://www.nlrb.gov/about-nlrb/rights-we-protect/your-rights). Pay specific attention to [Weingarten rights](https://www.nlrb.gov/about-nlrb/rights-we-protect/your-rights/weingarten-rights) which is the right to union representation during certain types of meetings with management. If you are ever unsure about your rights, please let a member of the L21HD leadership team know.

## About

Local 21HD is a union of epidemiologists, disease research investigation specialists, social research scientists, psychiatric evaluation specialists, and environmental scientists working at Public Health - Seattle & King County.

[We are part of Council 2 of the American Federation of State, County, and Municipal Employees (AFSCME)](https://council2.com/)

### [Enroll now!](https://council2.secureinput.org/membership-applications)

## Contact Information

Please send most questions to union\@local21hd.org OR contact Daniel via teams chat.

## Union Leadership

Staff Representative: Suzette Dickerson - suzetted\@council2.com

President: Daniel Casey - president\@local21hd.org

Vice-President: Sara Jaye Sanford

Secretary: Jessica Oda

Treasurer: Ron Buie

Harboview/First Hill Steward: Zach Tolley

PES Steward: Ryan Scott

Prevention Steward: \[TBD\]

Health Sciences (and other divisions): Carrie Lippy

## 
